name: Bug Report
description: File a bug report to help us improve
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: environment
    attributes:
      label: Environment
      description: What environment are you running in?
      placeholder: ex. Windows Server 2022, AWS us-west-2, SQL Server 2022 Standard
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What steps can we follow to reproduce this issue?
      placeholder: |
        1. Configure settings.json with...
        2. Run Start-FciDeployment.ps1
        3. See error...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell
